name: DevSecOps Integration

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest .

  security-scan:
    name: Security Scans
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Trivy Scan
        run: |
          docker run --rm aquasec/trivy image ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest > trivy-report.html

      - name: Run Snyk Scan
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest
          args: --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1

  push-to-dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest