name: DevSecOps Integration

on:
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t devsecure-api:latest .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecure-api:latest
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

      - name: Run Snyk Scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: devsecure-api:latest
          args: --file=Dockerfile --json-file-output=snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name : install snyk-to-html
        run: |
          npm install -g snyk-to-html

      - name: Generate Snyk HTML Report
        run: |
          snyk-to-html -i snyk-report.json -o snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.html

      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  push-to-dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t devsecure-api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag devsecure-api:latest ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest